// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPagesMovie.Data;

#nullable disable

namespace RazorPagesMovie.Migrations
{
    [DbContext(typeof(DoltContext))]
    partial class DoltContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_bin")
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("RazorPagesMovie.Models.Branch", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Hash")
                        .HasColumnType("longtext")
                        .HasColumnName("hash");

                    b.Property<DateTime?>("LatestCommitDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("latest_commit_date");

                    b.Property<string>("LatestCommitMessage")
                        .HasColumnType("longtext")
                        .HasColumnName("latest_commit_message");

                    b.Property<string>("LatestCommitter")
                        .HasColumnType("longtext")
                        .HasColumnName("latest_committer");

                    b.Property<string>("LatestCommitterEmail")
                        .HasColumnType("longtext")
                        .HasColumnName("latest_committer_email");

                    b.HasKey("Name");

                    b.ToTable("dolt_branches", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("RazorPagesMovie.Models.Commit", b =>
                {
                    b.Property<string>("CommitHash")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("commit_hash");

                    b.Property<string>("Committer")
                        .HasColumnType("longtext")
                        .HasColumnName("committer");

                    b.Property<string>("CommitterEmail")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<string>("Message")
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.HasKey("CommitHash");

                    b.ToTable("dolt_log", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("RazorPagesMovie.Models.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Genre")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Movie");
                });

            modelBuilder.Entity("RazorPagesMovie.Models.MovieDiff", b =>
                {
                    b.Property<string>("DiffType")
                        .HasColumnType("longtext")
                        .HasColumnName("diff_type");

                    b.Property<string>("FromGenre")
                        .HasColumnType("longtext")
                        .HasColumnName("from_genre");

                    b.Property<int?>("FromId")
                        .HasColumnType("int")
                        .HasColumnName("from_id");

                    b.Property<decimal?>("FromPrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("from_price");

                    b.Property<DateTime?>("FromReleaseDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("from_releasedate");

                    b.Property<string>("FromTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("from_title");

                    b.Property<string>("ToGenre")
                        .HasColumnType("longtext")
                        .HasColumnName("to_genre");

                    b.Property<int?>("ToId")
                        .HasColumnType("int")
                        .HasColumnName("to_id");

                    b.Property<decimal?>("ToPrice")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("to_price");

                    b.Property<DateTime?>("ToReleaseDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("to_releasedate");

                    b.Property<string>("ToTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("to_title");

                    b.ToTable("MovieDiff", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
